<?php
/**
 *
 * This file is part of the Finnish language pack
 *
 * @copyright (c) phpBB Suomi <https://www.phpbbsuomi.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
    exit;
}

if (empty($lang) || !is_array($lang))
{
    $lang = array();
}

$lang = array_merge($lang, array(
    'HELP_BBCODE_BLOCK_IMAGES'	=> 'Kuvien näyttäminen viesteissä',
    'HELP_BBCODE_BLOCK_INTRO'	=> 'Esittely',
    'HELP_BBCODE_BLOCK_LINKS'	=> 'Linkkien luominen',
    'HELP_BBCODE_BLOCK_LISTS'	=> 'Listojen luominen',
    'HELP_BBCODE_BLOCK_OTHERS'	=> 'Muut asiat',
    'HELP_BBCODE_BLOCK_QUOTES'	=> 'Määrämittaisen tekstin lainaaminen ja tulostaminen',
    'HELP_BBCODE_BLOCK_TEXT'	=> 'Tekstin muotoilu',

    'HELP_BBCODE_IMAGES_ATTACHMENT_ANSWER'	=> 'Liitetiedostot voidaan nyt sijoittaa mihin tahansa viestin osaan käyttämällä uutta <strong>[attachment=][/attachment]</strong> BBCodea, jos foorumin ylläpitäjä on sallinut liitetiedostojen käyttämisen ja jos sinulla on tarvittavat oikeudet liitetiedostojen luontiin. Viestin lähettämisruudussa on pudotusvalikko (tai painike) liitetiedostojen sisällyttämiseksi viestiin.',
    'HELP_BBCODE_IMAGES_ATTACHMENT_QUESTION'	=> 'Liitetiedostojen lisääminen viestiin',
    'HELP_BBCODE_IMAGES_BASIC_ANSWER'	=> 'phpBB:n BBCode sisältää tagin kuvien liittämiseksi viestiin. Tätä tagia käytettäessä on kaksi tärkeää muistettavaa asiaa: monet käyttäjät eivät arvosta suurta määrää kuvia viesteissä ja toiseksi kuvien täytyy olla jo saatavilla internetissä (se ei voi olla sinun koneellasi esimerkiksi, ellet aja www-palvelinta). Näyttääksesi kuvan, sinun täytyy ympäröidä kuvaan osoittava URL <strong>[img][/img]</strong> tageilla. Esimerkiksi:<br /><br /><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br /><br />Kuten yllä olevassa URL-osiossa mainittiin, voit ympäröidä kuvan <strong>[url][/url]</strong> tagilla halutessasi.<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br /><br />näyttäisi tältä:<br /><br /><a href="https://www.phpbb.com/"><img src="https://www.phpbb.com/theme/images/logos/blue/160x52.png" alt="" /></a>',
    'HELP_BBCODE_IMAGES_BASIC_QUESTION'	=> 'Kuvan lisääminen viestiin',

    'HELP_BBCODE_INTRO_BBCODE_ANSWER'	=> 'BBCode on erityinen toteutus HTML:stä. BBCoden käyttämisestä viesteissä määrää foorumin ylläpitäjä. Voit myös poistaa BBCoden käytöstä yksittäisistä viesteistä kirjoituslomakkeen kautta. BBCode itsessään on samankaltainen HTML:n kanssa. Tagit suljetaan hakasulkujen [ ja ] sisään sen sijaan että käytettäisiin &lt; ja &gt; -merkkejä. Se tarjoaa myös paremman kontrollin sen suhteen, miten asiat näytetään. Käytössä olevasta teemasta riippuen BBCoden lisääminen viesteihin voi olla helpompaa klikkailtavan käyttöliittymän kautta, joka sijaitsee viestikentän yläpuolella viestin lähetyslomakkeella. Saatat joka tapauksessa havaita seuraavan oppaan hyödylliseksi.*',
    'HELP_BBCODE_INTRO_BBCODE_QUESTION'	=> 'Mikä on BBCode?',

    'HELP_BBCODE_LINKS_BASIC_ANSWER'	=> 'phpBB:n BBCode tukee useita tapoja luoda linkkejä (URL).<ul><li>Ensimmäinen näistä käyttää <strong>[url=][/url]</strong> tagia. Mitä tahansa kirjoitat =-merkin jälkeen, toimii linkkinä. Esimerkiksi linkki osoitteeseen phpBB.com näyttäisi tältä:<br /><br /><strong>[url=https://www.phpbb.com/]</strong>Vieraile phpBB-sivustolla!<strong>[/url]</strong><br /><br />Tämä loisi seuraavanlaisen linkin: <a href="https://www.phpbb.com/">Vieraile phpBB-sivustolla!</a> Huomaathan, että linkki avautuu samaan ikkunaan tai uuteen ikkunaan riippuen käyttäjän selaimen asetuksista.</li><li>Jos haluat, että osoite itsessään näytetään linkkinä, voit käyttää yksinkertaisesti seuraavaa:<br /><br /><strong>[url]</strong>https://www.phpbb.com/<strong>[/url]</strong><br /><br />Tämä loisi seuraavanlaisen linkin: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a></li><li>Lisäksi phpBB tukee ominaisuutta nimeltään <i>taikalinkit</i>. Tämä ominaisuus muuttaa kaikki muodoltaan toimivat URLit linkeiksi ilman, että sinun tarvitsee määritellä yhtään tageja tai alussa olevaa http:// -osaa. Esimerkiksi kirjoittamalla www.phpbb.com viestiisi, se muuttuu muotoon <a href="http://www.phpbb.com/">www.phpbb.com</a> viestiä katsottaessa.</li><li>Sama pätee myös sähköpostiosoitteisiin. Voit joko määritellä sähköpostiosoitteen yksiselitteisesti:<br /><br /><strong>[email]</strong>no.one@domain.adr<strong>[/email]</strong><br /><br />joka muuttuu muotoon <a href="mailto:no.one@domain.adr">no.one@domain.adr</a> tai voit vain kirjoittaa no.one@domain.adr viestiisi ja se muutetaan automaattisesti kun tarkastelet viestiä.</li></ul>Kuten muiden BBCode-tagien kanssa, voit käyttää linkkejä muiden tagien ympärillä. Esimerkiksi <strong>[img][/img]</strong> (katso seuraava kohta), <strong>[b][/b]</strong>, jne. Kuten muotoilutagien kanssa, on sinun vastuulla varmistaa, että aloittavien ja lopettavien tagien järjestys on oikea. Esimerkiksi:<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/url][/img]</strong><br /><br /><span style="text-decoration: underline">ei</span> ole oikein, mikä voi johtaa viestisi poistoon, joten ole tarkkana.',
    'HELP_BBCODE_LINKS_BASIC_QUESTION'	=> 'Toiselle sivustolle linkittäminen',

    'HELP_BBCODE_LISTS_ORDERER_ANSWER'	=> 'Toinen listatyyppi, järjestetty lista, antaa sinulle mahdollisuuden hallita mitä tulostetaan ennen jokaista kohtaa. Järjestetty lista luodaan kirjoittamalla <strong>[list=1][/list]</strong> numeroidun listan luomista varten. Vaihtoehtoisesti voit luoda aakkostetun listan käyttämällä <strong>[list=a][/list]</strong> versiota. Kuten järjestämättömien listojen kanssa, jokainen listakohta aloitetaan <strong>[*]</strong> merkinnällä. Esimerkiksi:<br /><br /><strong>[list=1]</strong><br /><strong>[*]</strong>Mene kauppaan<br /><strong>[*]</strong>Osta uusi tietokone<br /><strong>[*]</strong>Karju tietokoneelle kun se kaatuu<br /><strong>[/list]</strong><br /><br />näyttäisi seuraavalta:<ol style="list-style-type: decimal;"><li>Mene kauppaan</li><li>Osta uusi tietokone</li><li>Karju tietokoneelle kun se kaatuu</li></ol>Aakkostettu lista näyttäisi tältä:<br /><br /><strong>[list=a]</strong><br /><strong>[*]</strong>Ensimmäinen vastaus<br /><strong>[*]</strong>Toinen vastaus<br /><strong>[*]</strong>Kolmas vastaus<br /><strong>[/list]</strong><br /><br />joka puolestaan tulostaa<ol style="list-style-type: lower-alpha"><li>Ensimmäinen vastaus</li><li>Toinen vastaus</li><li>Kolmas vastaus</li></ol><br /><strong>[list=A]</strong><br /><strong>[*]</strong>Ensimmäinen vastaus<br /><strong>[*]</strong>Toinen vastaus<br /><strong>[*]</strong>Kolmas vastaus<br /><strong>[/list]</strong><br /><br />tulostaisi<ol style="list-style-type: upper-alpha"><li>Ensimmäinen vastaus</li><li>Toinen vastaus</li><li>Kolmas vastaus</li></ol><br /><strong>[list=i]</strong><br /><strong>[*]</strong>Ensimmäinen vastaus<br /><strong>[*]</strong>Toinen vastaus<br /><strong>[*]</strong>Kolmas vastaus<br /><strong>[/list]</strong><br /><br />tulostaisi<ol style="list-style-type: lower-roman"><li>Ensimmäinen vastaus</li><li>Toinen vastaus</li><li>Kolmas vastaus</li></ol><br /><strong>[list=I]</strong><br /><strong>[*]</strong>Ensimmäinen vastaus<br /><strong>[*]</strong>Toinen vastaus<br /><strong>[*]</strong>Kolmas vastaus<br /><strong>[/list]</strong><br /><br />tulostaa<ol style="list-style-type: upper-roman"><li>Ensimmäinen vastaus</li><li>Toinen vastaus</li><li>Kolmas vastaus</li></ol>',
    'HELP_BBCODE_LISTS_ORDERER_QUESTION'	=> 'Järjestetyn listan luominen',
    'HELP_BBCODE_LISTS_UNORDERER_ANSWER'	=> 'BBCode tukee kahden tyyppisiä listoja: järjestämättömiä ja järjestettyjä. Ne ovat käytännössä samat kuin niiden HTML-vastineet. Järjestämätön listä tulostaa jokaisen kohdan peräkkäin sisennettynä listamerkillä. Luodaksesi järjestämättömän listan, voit käyttää <strong>[list][/list]</strong> tagia ja määritellä jokaisen kohdan listassa käyttämällä <strong>[*]</strong>. Esimerkiksi listataksesi suosikkivärisi, voisit käyttää:<br /><br /><strong>[list]</strong><br /><strong>[*]</strong>Punainen<br /><strong>[*]</strong>Sininen<br /><strong>[*]</strong>Keltainen<br /><strong>[/list]</strong><br /><br />Tämä loisi listan joka näyttäisi tältä:<ul><li>Punainen</li><li>Sininen</li><li>Keltainen</li></ul><br />Vaihtoehtoisesti voit määritellä listamerkkien tyylin käyttämällä joko <strong>[list=disc][/list]</strong>, <strong>[list=circle][/list]</strong> tai <strong>[list=square][/list]</strong>.',
    'HELP_BBCODE_LISTS_UNORDERER_QUESTION'	=> 'Järjestämättömän listan luominen',

    'HELP_BBCODE_OTHERS_CUSTOM_ANSWER'	=> 'Jos olet foorumin ylläpitäjä ja sinulla on oikeanlaiset oikeudet, voit lisätä mukautettuja BBCodeja hallintapaneelissa.',
    'HELP_BBCODE_OTHERS_CUSTOM_QUESTION'	=> 'Voinko lisätä omia tageja?',

    'HELP_BBCODE_QUOTES_CODE_ANSWER'	=> 'Jos haluat tulostaa palan koodia, tai itseasiassa mitä tahansa, joka vaatii tasalevyisen fontin, kuten Courier -tyyppisen fontin, sinun kannattaa ympäröidä tekstisi <strong>[code][/code]</strong> tageilla, esim. <br /><br /><strong>[code]</strong>echo &quot;Tässä on koodia&quot;;<strong>[/code]</strong><br /><br />Kaikki <strong>[code][/code]</strong> tagien sisällä käytetty muotoilu säilytetään, kun myöhemmin tarkastelet sitä. PHP syntaksin korostus voidaan ottaa käyttöö käyttämällä <strong>[code=php][/code]</strong> ja on suositeltava tapa, kun lähetät PHP-koodipätkiä, jotta se olisi luettavampaa.',
    'HELP_BBCODE_QUOTES_CODE_ANSWER'	=> 'Jos haluat tulostaa palan koodia tai itseasiassa mitä tahansa joka tarvii tasalevyisen fontin, kuten Courier -tyyppisen fontin, sinun tulee laittaa teksti <strong>[code][/code]</strong>-tagien väliin, esim.<br /><br /><strong>[code]</strong>echo &quot;Tässä on vähän koodia&quot;;<strong>[/code]</strong><br /><br />Kaikki muotoilu <strong>[code][/code]</strong>-tagien välissä säilytetään.',
    'HELP_BBCODE_QUOTES_CODE_QUESTION'	=> 'Koodin tai tasalevyisen datan lisääminen',
    'HELP_BBCODE_QUOTES_TEXT_ANSWER'	=> 'Tekstin lainaamiseen on kaksi tapaa. Viittauksen kanssa tai ilman viittausta.<ul><li>Kun käytät Lainaa-toimintoa, voit huomata, että teksti lainataan viestiruudussa <strong>[quote=&quot;&quot;][/quote]</strong> lohkolla ympäröitynä. Tämä tapa mahdollistaa tekstin lainauksen viittaamalla henkilöön tai mihin tahansa muuhun haluaamasi asiaan! Esimerkiksi lainataksesi pätkän tekstiä herra Aakkoselta, syöttäisit:<br /><br /><strong>[quote=&quot;herra Aakkonen&quot;]</strong>Herra Aakkosen kirjoittama teksti tulee tähän<strong>[/quote]</strong><br /><br />Lopputulos lisää automaattisesti &quot;herra aakkonen kirjoitti:&quot; -tekstin ennen varsinaista lainattua tekstiä. Muista että sinun <strong>täytyy</strong> käyttää lainausmerkkejä &quot;&quot; nimen ympärillä, jota käytät launauksen lähteenä. Lainausmerkit eivät ole valinnaisia.</li><li>Toinen tapa sallii sinun lainata vain jotain ilman viitteitä. Voit tehdä sen laittamalla lainaamasi tekstin <strong>[quote][/quote]</strong> tagien sisään. Kun katsot viestiä, näkyy teksti yksinkertaisesti lainausosion sisällä.</li></ul>',
    'HELP_BBCODE_QUOTES_TEXT_QUESTION'	=> 'Tekstin lainaaminen vastauksissa',

    'HELP_BBCODE_TEXT_BASIC_ANSWER'	=> 'BBCode sisältää tageja, jotka mahdollistavat tekstin muotoilun nopeasti. Tämä käy seuraavasti: <ul><li>Lihavoidaksesi tekstin, ympäröi se <strong>[b][/b]</strong>-tageilla. esim. <br /><br /><strong>[b]</strong>Terve<strong>[/b]</strong><br /><br />näyttäisi tältä <strong>Terve</strong></li><li>Alleviivaukseen käytä <strong>[u][/u]</strong>. Esimerkiksi:<br /><br /><strong>[u]</strong>Huomenta<strong>[/u]</strong><br /><br />näyttäisi seuraavalta: <span style="text-decoration: underline">Huomenta</span></li><li>Kursivoidaksesi tekstin, käytä <strong>[i][/i]</strong>, esim.<br /><br />Tämä on <strong>[i]</strong>Hienoa!<strong>[/i]</strong><br /><br /> tulostaisi Tämä on <i>Hienoa!</i></li></ul>',
    'HELP_BBCODE_TEXT_BASIC_QUESTION'	=> 'Kuinka tehdä lihavoitua, alleviivattua ja kursivoitua tekstiä?',
    'HELP_BBCODE_TEXT_COLOR_ANSWER'	=> 'Vaihtaaksesi tekstisi väriä tai kokoa, voit käyttää seuraavia tageja. Pidä kuitenkin mielessä, että se miltä lopputulos näyttää, riippuu katsojan selaimesta ja järjestelmästä: <ul><li>Tekstin värin vaihtaminen onnistuu ympäröimällä se <strong>[color=][/color]</strong> tageilla. Voit määritellä tunnetun värin nimen, (esim. red, blue, yellow, jne.) tai kolmen heksadesimaalin muodostaman värikoodin, esimerkiksi #FFFFFF, #000000. Luodaksesi punaista tekstiä, voisit käyttää:<br /><br /><strong>[color=red]</strong>Terve!<strong>[/color]</strong><br /><br />tai<br /><br /><strong>[color=#FF0000]</strong>Terve!<strong>[/color]</strong><br /><br />Molemmat näyttävät tältä: <span style="color:red">Terve!</span></li><li>Tekstin kokoa voidaan muuttaa vastaavasti käyttämällä <strong>[size=][/size]</strong>. Tämän tagin toiminta riippuu käyttäjän käytössä olevasta teemasta, mutta suositeltu arvo on numero, joka määrittelee fontin koon prosentteinaalkaen arvosta 20 (hyvin pieni) arvoon 200 (hyvin suuri) oletuksena. Esimerkiksi:<br /><br /><strong>[size=30]</strong>PIENI<strong>[/size]</strong><br /><br />on yleensä <span style="font-size:30%;">PIENI</span><br /><br />kun puolestaan:<br /><br /><strong>[size=200]</strong>SUURI!<strong>[/size]</strong><br /><br />olisi <span style="font-size:200%;">SUURI!</span></li></ul>',
    'HELP_BBCODE_TEXT_COLOR_QUESTION'	=> 'Kuinka vaihtaa tekstin väriä tai kokoa?',
    'HELP_BBCODE_TEXT_COMBINE_ANSWER'	=> 'Kyllä, tottakai voit. Esimerkiksi jos haluat saada jonkun huomion, voisit kirjoittaa:<br /><br /><strong>[size=200][color=red][b]</strong>KATSOKAA MINUA!<strong>[/b][/color][/size]</strong><br /><br />tämä näyttäisi seuraavalta: <span style="color:red;font-size:200%;"><strong>KATSOKAA MINUA!</strong></span><br /><br />Emme kuitenkaan suosittele kirjoittamaan paljon tämän näköistä tekstiä! Muista, että se on sinun, kirjoittajan, vastuulla varmistaa, että tagit on suljettu oikein. Esimerkiksi seuraava on väärin::<br /><br /><strong>[b][u]</strong>Tämä on väärin<strong>[/b][/u]</strong>',
    'HELP_BBCODE_TEXT_COMBINE_QUESTION'	=> 'Voinko yhdistää muotoilutageja?',
));
